[package]
name = "flashfunk"
version = "0.1.0"
authors = ["somewheve <somewheve@gmail.com>"]
edition = "2018"
include = ["src/**/*", "sdk_sources/**/*", "Cargo.toml", "build.rs"]

build = "build.rs"

[workspace]
members = ["flashfunk-codegen"]

[dependencies]
chrono = { version = "0.4.13", default-features = false, features = ["clock"] }
crossbeam-queue = { git = "https://github.com/stjepang/crossbeam", branch = "spsc" }
encoding = "0.2.33"
libc = "0.2.0"
derive_more ="0.99.10"

[dev-dependencies]
flashfunk-codegen = { path = "./flashfunk-codegen" }

[[example]]
name = "login"
[[example]]
name = "call"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
debug-assertions = false
overflow-checks = false
panic = "abort"

[profile.dev]
rpath = true

[build-dependencies]
bindgen = { git ="https://github.com/rust-lang/rust-bindgen.git", branch = "master", default-features = false }
cc = "1.0"