[package]
name = "ctpbee-rs"
version = "0.1.0"
authors = ["somewheve <somewheve@gmail.com>"]
edition = "2018"
include = ["src/**/*", "sdk_sources/**/*", "Cargo.toml", "build.rs"]

build = "build.rs"

[dependencies]

chrono = { version = "0.4.13", default-features = false, features = ["clock"] }

libc = "0.2.0"
encoding = "0.2.33"
crossbeam-queue = { git = "https://github.com/stjepang/crossbeam", branch = "spsc" }

[[example]]
name = "login"
[[example]]
name = "call"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
debug-assertions = false
overflow-checks = false
panic = "abort"

[profile.dev]
rpath = true

[build-dependencies]
bindgen = { git ="https://github.com/rust-lang/rust-bindgen.git", branch = "master", default-features = false }
cc = "1.0"