[package]
name = "ctpbee-rs"
version = "0.1.0"
authors = ["somewheve <somewheve@gmail.com>"]
edition = "2018"
include = ["src/**/*", "Cargo.toml", "build.rs"]
build = "build.rs"
[dependencies]
chrono = "0.4.13"
libc = "0.2.0"
actix = "0.10.0-alpha.3"
actix-rt = "1.1.1"
futures = "0.3.5"
failure = "0.1"
encoding = "0.2.33"
memchr = "2.3.3"
simple-error = "0.2.1"

[[example]]
name = "login"


[lib]
name = "ctpbee_rs"
path = "src/lib.rs"

[build-dependencies]
bindgen = "0.52"
cc = "1.0"