[package]
name = "flashfunk-core"
version = "0.4.0"
authors = ["somewheve <somewheve@gmail.com>"]
edition = "2018"
include = ["src/**/*", "sdk_sources/**/*", "Cargo.toml", "build.rs"]

build = "build.rs"

[features]
default = []
mock = ["tokio"]

[dependencies]
ahash = "0.4.5"
bitflags = "1.2.1"
cache-padded = "1.1.1"
chrono = { version = "0.4.13", default-features = false, features = ["clock"] }
core_affinity = "0.5.10"
encoding = "0.2.33"
libc = "0.2.0"
tokio = { version = "0.3", features = ["rt", "time"], optional = true }

[dev-dependencies]
flashfunk-codegen = { path = "../flashfunk-codegen" }
flashfunk-fetcher = { path = "../flashfunk-fetcher" }

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
debug-assertions = false
overflow-checks = false
panic = "abort"

[profile.dev]
rpath = true

[build-dependencies]
bindgen = "0.55.1"
cc = "1.0"